
import React from 'react';

interface AboutPageProps {
    onBack: () => void;
}

const AboutPage: React.FC<AboutPageProps> = ({ onBack }) => {
    return (
        <div className="animate-fade-in max-w-4xl mx-auto bg-white p-6 sm:p-8 rounded-xl shadow-md">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">About the Quad-Factor Stock Analyzer</h2>

            <div className="space-y-6 text-slate-700">
                <section>
                    <h3 className="text-xl font-semibold text-slate-800 mb-2">Purpose of This Application</h3>
                    <p>
                        The Quad-Factor Stock Analyzer is an advanced tool designed to empower investors by providing a holistic and AI-driven perspective on stocks. Our goal is to synthesize complex market data into a clear, actionable analysis. We look at four key pillars—technical indicators, market sentiment, fundamental financial health, and your personal risk profile—to generate a comprehensive investment strategy.
                    </p>
                </section>

                <section>
                    <h3 className="text-xl font-semibold text-slate-800 mb-2">How We Use AI</h3>
                    <p>
                        This application leverages Google's powerful Gemini model to perform its analysis. When you request an analysis, the app does the following:
                    </p>
                    <ul className="list-disc list-inside mt-2 space-y-1 pl-4">
                        <li><strong>Gathers Real-time Data:</strong> The AI uses Google Search to find the latest news, analyst ratings, social media trends, and financial reports related to the stock.</li>
                        <li><strong>Synthesizes Information:</strong> It processes this vast amount of information, identifying key strengths, weaknesses, opportunities, and threats.</li>
                        <li><strong>Calculates Scores:</strong> The AI evaluates the data to generate the Quad-Factor scores (Technical, Sentiment, and Risk-Alignment) and provides a rationale for each.</li>
                        <li><strong>Personalizes Strategy:</strong> Finally, it tailors its investment rationale and trade strategy suggestions to align with the risk profile you select (Conservative, Moderate, or Aggressive).</li>
                    </ul>
                </section>

                <section className="p-4 bg-amber-50 border-l-4 border-amber-400 rounded-r-lg">
                    <h3 className="text-xl font-semibold text-amber-800 mb-2">Important Disclaimer</h3>
                    <p className="text-amber-900">
                        The Quad-Factor Stock Analyzer is an informational tool and should not be considered as financial advice. The content generated by the AI is for educational and illustrative purposes only. All investments involve risk, and the past performance of a security does not guarantee future results. You should always conduct your own research and consult with a qualified financial advisor before making any investment decisions. We are not liable for any losses or damages arising from the use of this application.
                    </p>
                </section>

                <div className="text-center pt-4">
                    <button
                        onClick={onBack}
                        className="px-6 py-2 text-base font-medium text-white bg-indigo-600 border border-transparent rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                    >
                        Back to Analyzer
                    </button>
                </div>
            </div>
        </div>
    );
};

export default AboutPage;